language: c
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - cmake
      - zip
      - bash-completion
      - git
      - xz-utils
      - debhelper
      - devscripts
      - libc6-dev:i386
      - libasound2:i386
      - libasound2-dev:i386
      - libssl-dev:i386
      - libssl0.9.8:i386
      - libfreetype6-dev:i386
      - libx11-dev:i386
      - libsm-dev:i386
      - libice-dev:i386
      - libgl1-mesa-glx:i386
      - libgl1-mesa-dev:i386
      - libxext-dev:i386
      - libglapi-mesa:i386
      - build-essential
      - gcc-multilib
      - g++
# to be able to execute a VM downloaded from the internet during build
      - lib32asound2
      - lib32z1
      - lib32ncurses5
      - lib32bz2-1.0
      - gvfs-daemons:i386

script: 
  - scripts/build.sh
# broken because it loads a pre-spur image
#  - scripts/test.sh

matrix:
# Ignore failures with OSX as the build forces to be build for OSX 10.6 and
# the header files are not installed and we can't install them on OSX. This
# could be easily fixed with a different CMakeLists.txt
  allow_failures:
    - os: osx
